version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-node
    steps:
      - checkout
      - run:
          name: Update SDK Tools
          command: $ANDROID_HOME/tools/bin/sdkmanager --update
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: ./Branch-SDK/build/outputs/aar/